### ISSUE TITLE
魅族手机切换导航方式再激活应用会卡住黑屏无响应

### ISSUE THREAD

**Issue by Atlan8** [thundersdata-frontend/rn-template#27]
机型：魅族16th plus
系统版本：Flyme 8.1.5.1A
安卓版本：8.1.0

操作步骤：
1. 使用 vscode 跑起应用
2. 在手机打开应用后，按home键回到系统主页
3. 前往系统设置将导航方式从 mBack 切换到 安卓导航栏
4. 回到系统主页，再次打开应用
5. 控制台就会出现报错信息，应用卡死黑屏无响应（如果没有出现就返回系统首页再次打开应用）

下面是控制台 log 的信息：
 LOG  Skipping setJSExceptionHandler: Reason: In DEV mode and allowedInDevMode = false
 LOG  Running "rnTemplate" with {"rootTag":1}
 LOG  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rntemplate/com.rntemplate.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2983)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3061)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4968)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1753)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:631)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
        at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
        at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:297)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
        at com.rntemplate.MainActivity.onCreate(MainActivity.java:42)
        at android.app.Activity.performCreate(Activity.java:7065)
        at android.app.Activity.performCreate(Activity.java:7056)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1216)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        ... 10 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
        ... 25 more
Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
        at com.swmansion.rnscreens.ScreenFragment.<init>(ScreenFragment.kt:42)
        ... 28 more

**Comment by chj-damon** [comment]
报错里面的这个解决办法你尝试了吗？

**Comment by qqack** [comment]
已经尝试解决了，可以试一下看看，我这边用魅族16th测试没有问题

**Comment by Atlan8** [comment]
不好意思哈最近这段时间有点忙，我刚才拉了下代码，发现模拟器能跑起来，安卓真机卡在启动页了，手机还是那台魅族。
下面是重启服务的log信息：

info Reloading app...
 BUNDLE  ./index.js 

 LOG  Skipping setJSExceptionHandler: Reason: In DEV mode and allowedInDevMode = false
 WARN  RCTBridge required dispatch_sync to load RNGestureHandlerModule. This may lead to deadlocks
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 LOG  Running "rnTemplate" with {"rootTag":111,"initialProps":{}}
 WARN  The native module for Flipper seems unavailable. Please verify that `react-native-flipper` is installed as yarn dependency to your project and, for iOS, that `pod install` is run in the `ios` directory. 
    at App (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:151069:52)
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:77307:36)
    at rnTemplate(RootComponent) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:83318:28)
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 ERROR  Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you ran `pod install` in the ios/ directory.
* Make sure you rebuilt the app., js engine: hermes 
    at Stack (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:245163:20)
    at EnsureSingleNavigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:156807:24)
    at BaseNavigationContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:156356:28)
    at ThemeProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:162368:21)
    at NavigationContainerInner (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:162244:26)
    at RCTView
    at View
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:152094:45)
    at Portal.Host (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:152540:37)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:152184:22)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:152249:19)
    at ThemeProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:151125:26)
    at RNCSafeAreaProvider
    at SafeAreaProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:163056:24)
    at App (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:151069:52)
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:77307:36)
    at rnTemplate(RootComponent) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:83318:28)
 ERROR  Error: Requiring module "src/services/StorageService.ts", which threw an exception: Error: Failed to create a new MMKV instance: The native MMKV Module could not be found.
* Make sure react-native-mmkv is correctly autolinked (run `npx react-native config` to verify)
* Make sure you ran `pod install` in the ios/ directory.
* Make sure you rebuilt the app., js engine: hermes 
    at Stack (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:245163:20)
    at EnsureSingleNavigator (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:156807:24)
    at BaseNavigationContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:156356:28)
    at ThemeProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:162368:21)
    at NavigationContainerInner (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:162244:26)
    at RCTView
    at View
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:152094:45)
    at Portal.Host (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:152540:37)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:152184:22)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:152249:19)
    at ThemeProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:151125:26)
    at RNCSafeAreaProvider
    at SafeAreaProvider (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:163056:24)
    at App (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:151069:52)
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:77307:36)
    at rnTemplate(RootComponent) (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:83318:28)
 ERROR  TypeError: Cannot read property 'storageService' of undefined

This error is located at:
    in Stack (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in RCTView (created by View)
    in View
    in Unknown (created by Portal.Host)
    in Portal.Host (created by ThemeProvider)
    in Unknown
    in Unknown (created by ThemeProvider)
    in ThemeProvider (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in rnTemplate(RootComponent), js engine: hermes
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'storageService' of undefined
TypeError: Cannot read property 'storageService' of undefined
    at Stack (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:245163:69)
    at renderWithHooks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:13402:33)
    at mountIndeterminateComponent (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:16190:34)
    at beginWork (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:17131:49)
    at beginWork$1 (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:20958:29)
    at performUnitOfWork (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:20369:29)
    at workLoopSync (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:20308:28)
    at renderRootSync (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:20284:25)
    at performSyncWorkOnRoot (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:20045:40)
    at flushSyncCallbacks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:10370:36)
    at flushSyncCallbacksOnlyInLegacyMode (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:10351:29)
    at scheduleUpdateOnFiber (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:19732:49)
    at dispatchAction (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:14377:43)
    at _callee$ (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:162708:27)
    at call (native)
    at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:24479:23)
    at invoke (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:24649:32)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:24521:30)
    at call (native)
    at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:24479:23)
    at invoke (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:24551:30)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:24561:21)
    at tryCallOne (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:30242:16)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:30343:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:30934:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:30830:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:30869:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:31079:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:5861:46)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:5639:45)
    at __guard (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:5844:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:5638:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=work.isee.quhuo122:5631:33)
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.
 WARN  Sending `didSendNetworkData` with no listeners registered.
 WARN  Sending `didReceiveNetworkResponse` with no listeners registered.
 WARN  Sending `didReceiveNetworkData` with no listeners registered.
 WARN  Sending `didCompleteNetworkResponse` with no listeners registered.

**Comment by Atlan8** [comment]
不好意思哈最近比较忙，我下午拉了代码，跑了一下发现没啥问题了，谢谢大佬
